package loader

import (
	pluginflatfs "github.com/ipfs/go-ipfs/plugin/plugins/flatfs"
	pluginlevelds "github.com/ipfs/go-ipfs/plugin/plugins/levelds"
	pluginpeerlog "github.com/ipfs/go-ipfs/plugin/plugins/peerlog"
)

// DO NOT EDIT THIS FILE
// This file is being generated as part of plugin build process
// To change it, modify the plugin/loader/preload.sh

func init() {
	Preload(pluginflatfs.Plugins...)
	Preload(pluginlevelds.Plugins...)
	Preload(pluginpeerlog.Plugins...)
}
