name = "bitswap"

[builders]
  "docker:go" = { enabled = false, enable_go_build_cache = false }

[runners]
  "local:docker" = { enabled = false }
  "cluster:k8s" = { enabled = false }

[global.build_config]
  enable_go_build_cache = true

[[testcases]]
  name = "speed-test"
  instances = { min = 2, max = 100, default = 2 }

  [testcases.params]
  size = { type = "int", desc = "size of file to transfer, in human-friendly form", default = "1MiB" }
  count = { type = "int", desc = "number of transfers", default = "10" }
